#!/bin/bash

if [ ! -t 0 ]; then
    input=$(cat)
elif [ -n "$1" ]; then
    input="$1"
else
    echo "Usage: $0 <input_string>"
    echo "   or: echo 'AtTgctT' | $0"
    exit 1
fi

output="${input//[Tt]/U}"
echo "$output"
