#!/usr/bin/env ruby

fasta = File.read(ARGV[0])

fastas = fasta
  .split('>').reject(&:empty?).map do |fasta|
    lines = fasta.split("\n")
    header = lines.first
    sequence = lines.drop(1).join('')

    name = header.split(/\s+/).first
    [name, sequence]
  end.to_h

fastas.keys.each do |key|
  puts key
end
