#!/usr/bin/ruby

file_content = `grep -A1 #{ARGV[0]} #{ARGV[1]}`

fastas = file_content
  .split('>').reject(&:empty?).map.with_index(1) do |fasta, i|
    lines = fasta.split("\n")
    header = lines.first
    sequence = lines.drop(1).join('')

    name = header.split(/\s+/).first + "-#{i}"
    [name, sequence]
  end.to_h

fastas.keys.combination(2).each do |pair|
  puts pair.join(' ')
  system("align \"#{fastas[pair[0]]}\" \"#{fastas[pair[1]]}\"")
end
