#!/usr/bin/env ruby

fasta_source = File.read(ARGV[0])
fasta_target = File.read(ARGV[1])

sources = fasta_source
  .split('>').reject(&:empty?).map do |fasta|
    lines = fasta.split("\n")
    header = lines.first

    name = header.split(/\s+/).first
    [name, header]
  end.to_h

targets = fasta_target
  .split('>').reject(&:empty?).map do |fasta|
    lines = fasta.split("\n")
    header = lines.first
    sequence = lines.drop(1).join('')

    name = header.split(/\s+/).first
    [name, sequence]
  end.to_h

targets.each do |name, sequence|
  source_header = sources[name]
  puts ">#{source_header}"
  puts sequence
end