#!/Users/kamal/.asdf/shims/ruby

require 'nokogiri'
require 'pry'
require 'json'

Dir.glob('./blosum_matrices/*').each do |file|
    File.open(file) do |f|
        doc = Nokogiri::HTML(f)
        # select pre.filecontent-src to get the content of the file
        content = doc.css('pre.filecontent-src')
            .text
            .split("\n")
            .drop(2)
        # select the first line of the content
        first_keys = content
            .first
            .split(' ')
            .map { |k| [k, Hash.new()] }.to_h

        content.drop(1).each do |line|
            line = line.split(' ')
            key = line.first
            line.drop(1).each_with_index do |value, i|
                first_keys[key][first_keys.keys[i]] = value.to_i
            end
        end

        File.open("blosum_matrices/#{file.split('/').last}.json", 'w') do |f|
            f.write(JSON.pretty_generate(first_keys))
        end
    end
end