#!/bin/bash

dna=`grep -A1 -i "$1" "$2" | tail -n 1`

if [ -z "$3" ]; then
    echo "$dna"
    exit 0
fi

start_index=$(( $3 - 1 ))

if [ -z "$4" ]; then
    echo "${dna:$start_index}"
    exit 0
fi

length=$(( $4 - $3 + 1 ))
echo "${dna:$start_index:$length}"
